export const site = {
  verein: {
    name: "Circus Akademie München e.V.",
    kurzbeschreibung: "Zeitgenössischer Zirkus als Kunstform – Training, Bühne, Wissenstransfer und Community in München.",
    mission: "Wir stärken den zeitgenössischen Zirkus in München: durch Räume, Formate und Zusammenarbeit, die künstlerische Entwicklung und kulturelle Teilhabe möglich machen.",
    intro: {
      title: "Circus Akademie München e.V.",
      text: "Circus Akademie München e.V. ist ein gemeinnütziger Verein mit Sitz in München. Zweck des Vereins ist die Förderung von Kunst und Kultur, insbesondere des zeitgenössischen Circus.",
      teaser: [
        "Circus als Brückenschlag zwischen darstellender und bildender Kunst",
        "Raum für neue Formate, neue Räume und Zusammenarbeit mit lokalen & internationalen Künstlern",
        "Beitrag zur Münchner Kulturlandschaft",
      ],
    },
    details: {
      sitz: "München",
      geschaeftsjahr: "Kalenderjahr",
      selbstverstaendnis: "Der Verein versteht den Circus als besondere Kunstform und fördert Formen des Zirkus auch jenseits des etablierten fahrenden Circus und Varietés – u. a. durch neue Räume und Veranstaltungsformen.",
      gemeinnuetzigkeit: {
        zweck: "Der Verein verfolgt ausschließlich und unmittelbar gemeinnützige Zwecke im Sinne der Abgabenordnung. Zweck ist die Förderung der Kunst und Kultur.",
        selbstlosigkeit: [
          "Der Verein ist selbstlos tätig und verfolgt nicht in erster Linie eigenwirtschaftliche Zwecke.",
          "Mittel werden nur für satzungsmäßige Zwecke verwendet.",
          "Keine Zuwendungen ohne Gegenleistung; keine Begünstigung durch zweckfremde Ausgaben oder unverhältnismäßige Vergütungen.",
        ],
      },
    },
  },
  hero: {
    headline: "Zeitgenössischer Zirkus braucht Raum.",
    subline: "Wir schaffen in München Struktur für Training, Austausch und Bühne – damit Ideen nicht in der Luft hängen, sondern fliegen lernen.",
    cta1: {
      text: "Mitmachen",
      href: "/mitmachen",
    },
    cta2: {
      text: "Kontakt",
      href: "/kontakt",
    },
    hinweis: "Ort 2025: Pepe Dome (Geodom am Ostpark)",
  },
  zweck: {
    kicker: "Wofür wir stehen",
    text: "Der Circus Akademie München e.V. setzt sich für die Förderung von Kunst und Kultur ein – mit Fokus auf zeitgenössischen Zirkus. Wir verstehen Zirkus als Brücke zwischen darstellender und bildender Kunst: Körper, Musik, Raum, Bild und Story treffen aufeinander. Unser Ziel ist eine verlässliche Struktur, in der Training, Wissenstransfer und öffentliche Formate dauerhaft möglich werden. Wir arbeiten gemeinschaftlich, sorgfältig und offen für Kooperationen – damit künstlerische Entwicklung und kulturelle Teilhabe in München wachsen können.",
    werte: ["Qualität", "Sicherheit", "Offenheit", "Zusammenarbeit"],
  },
  angebote: [
    {
      id: "open-stage",
      title: "Open Stage",
      teaser: "Ein Raum zum Experimentieren: interdisziplinär, niedrigschwellig, publikumsnah.",
      details: "Unsere Open Stages schaffen Sichtbarkeit und Austausch. Artistik trifft Musik, Performance trifft Bild, Recherche trifft Publikum. Wer Neues ausprobiert, braucht einen Rahmen – wir bauen ihn gemeinsam.",
      bullets: ["Testen & Feedback", "Vernetzung", "Dokumentation/Material nach Möglichkeit"],
      image: "/placeholders/program-1.svg",
      volltext: "Open-Stage-Format: Raum zum Experimentieren, mit möglichst interdisziplinärer Vernetzung (Artistik, Musik, bildende & darstellende Kunst).",
      cta: "Du möchtest dich bei einer Open Stage beteiligen?",
      ctaLink: "/kontakt?subject=Open%20Stage",
    },
    {
      id: "training",
      title: "Training",
      teaser: "Regelmäßige Trainings- und Probenmöglichkeiten als Basis für Kontinuität.",
      details: "Kontinuität ist im Zirkus alles. Wir arbeiten daran, Trainingsfenster, Probenzeiten und Austausch so zu organisieren, dass Entwicklung planbarer wird – für unterschiedliche Level und Disziplinen.",
      bullets: ["Struktur & Routine", "Sicherer Rahmen", "Community-Training"],
      image: "/placeholders/program-2.svg",
      volltext: "Workshops & Training / Bildungsangebote: Entwicklung künstlerischer Fähigkeiten fördern.",
      cta: "Du suchst regelmäßige Trainingsmöglichkeiten?",
      ctaLink: "/kontakt?subject=Training",
    },
    {
      id: "workshops",
      title: "Workshops",
      teaser: "Weiterbildung mit Gästen und lokalen Expert*innen – von Technik bis Kreation.",
      details: "Workshops bringen neue Impulse nach München. Von Grundlagen bis Spezialthemen: Technik, Körperarbeit, Kreation, Bühnenpraxis. Inhalte und Formate entwickeln wir bedarfsorientiert.",
      bullets: ["Skill-Boost", "Input von außen", "Gemeinsames Lernen"],
      image: "/placeholders/program-3.svg",
      volltext: "Workshops & Training / Bildungsangebote: Entwicklung künstlerischer Fähigkeiten fördern.",
      cta: "Du interessierst dich für einen Workshop?",
      ctaLink: "/kontakt?subject=Workshop",
    },
    {
      id: "produktionen",
      title: "Produktionen",
      teaser: "Ressourcen, Austausch und Sichtbarkeit für performative Projekte.",
      details: "Wir unterstützen Projekte ideell und organisatorisch – durch Raum, Netzwerk, Sparring und Öffentlichkeit, wenn es passt. Ziel: mehr zeitgenössischer Zirkus auf Münchner Bühnen und in neuen Räumen.",
      bullets: ["Netzwerk & Kooperation", "Strukturhilfe", "Bühnenmomente"],
      image: "/placeholders/program-4.svg",
      volltext: "Förderung performativer Projekte: finanziell oder ideell, besonders im zeitgenössischen Circus. Aufführungen organisieren & durchführen: Präsentationsmöglichkeiten für Zirkus-Künstler und Bekanntmachung des zeitgenössischen Circus. Information & Austausch: Informationen verbreiten, Fachtagungen und fachlicher Austausch.",
      cta: "Du hast ein Projekt, das Unterstützung braucht?",
      ctaLink: "/kontakt?subject=Produktion",
    },
  ],
  ort: {
    kicker: "Unser Ort",
    headline: "Pepe Dome (Geodom am Ostpark)",
    text: "Seit 2025 haben wir mit dem Pepe Dome eine feste Basis in München. Hier können Trainings, Proben, Workshops und kleine Formate verlässlicher stattfinden. Der Raum ist unser Anker – und gleichzeitig ein Startpunkt für Kooperationen in der Stadt.",
    fakten: [
      "München – Ostpark",
      "Nutzung für Training/Proben/Workshops",
      "Formate nach Absprache",
      "Kooperationen willkommen",
      "Platz für Community & Austausch",
    ],
    mapImage: "/placeholders/map.svg",
    trainingszeiten: {
      profis: "Mo-Fr 11:00-14:00",
      beschreibung: "Aktuelle Trainingszeiten im Geodome für Profis",
    },
  },
  aktuelles: [
    {
      date: "2026-01-18",
      title: "Open Stage: Winter Edition",
      description: "Kurze Nummern, neue Ideen, offenes Feedback. Details folgen.",
    },
    {
      date: "2026-02-08",
      title: "Workshop-Wochenende",
      description: "Thema und Dozent*in werden zeitnah veröffentlicht.",
    },
    {
      date: "2026-03-15",
      title: "Community-Training Slot",
      description: "Gemeinsam trainieren, austauschen, dranbleiben.",
    },
  ],
  mitmachen: [
    {
      id: "mitglied",
      title: "Mitglied werden",
      text: "Werde Teil des Vereins und gestalte Struktur, Angebote und Formate mit.",
      cta: "Mitglied anfragen",
      subject: "Mitgliedschaft",
      details: {
        wer: "Jede natürliche Person sowie juristische Person, die die Zwecke des Vereins aktiv oder ideell unterstützt. Über den schriftlichen Aufnahmeantrag entscheidet der Vorstand.",
        arten: [
          "Aktive Mitglieder: mit Stimmrecht in der Mitgliederversammlung",
          "Fördermitglieder: ohne Stimmrecht",
        ],
        beitrag: "Der Mitgliedsbeitrag beträgt 35€ pro Jahr. Die Fälligkeit beschließt die Mitgliederversammlung. Es gilt die jeweils gültige Beitragsordnung.",
        austritt: "Austritt: schriftlich, bis 3 Monate vor Jahresende. Ausschluss: bei wichtigem Grund (z. B. grober Verstoß, Zahlungsrückstand); Entscheidung durch Vorstand, vorherige Anhörung möglich.",
      },
    },
    {
      id: "unterstuetzen",
      title: "Unterstützen",
      text: "Du willst fördern, spenden oder Ressourcen teilen? Jede Unterstützung stärkt Kultur vor Ort.",
      cta: "Unterstützung anbieten",
      subject: "Unterstützen",
      details: {
        wertversprechen: "Ihre Unterstützung ermöglicht zeitgenössischen Zirkus in München: Wir schaffen Räume für künstlerische Entwicklung, fördern lokale Talente und bereichern die Münchner Kulturlandschaft nachhaltig.",
        spenden: {
          titel: "Spenden",
          text: "Jede Spende hilft uns, Trainingsräume zu sichern, Workshops zu organisieren und künstlerische Projekte zu fördern. Als gemeinnütziger Verein können wir Spendenquittungen ausstellen.",
          vorteile: [
            "Steuerlich absetzbar (gemeinnütziger Verein)",
            "Direkte Förderung der Münchner Kulturlandschaft",
            "Unterstützung lokaler Künstler*innen",
            "Transparente Mittelverwendung",
          ],
          betraege: [
            { betrag: "50€", beschreibung: "Unterstützt einen Workshop-Tag" },
            { betrag: "100€", beschreibung: "Ermöglicht Probenzeit für ein Projekt" },
            { betrag: "250€", beschreibung: "Fördert eine Open Stage Veranstaltung" },
            { betrag: "500€+", beschreibung: "Ermöglicht größere Projekte und Formate" },
          ],
        },
        sponsoring: {
          titel: "Sponsoring",
          text: "Als Sponsor unterstützen Sie zeitgenössischen Zirkus und erhalten gleichzeitig wertvolle Sichtbarkeit für Ihr Unternehmen oder Ihre Organisation.",
          vorteile: [
            "Sichtbarkeit bei Veranstaltungen und auf unserer Website",
            "Assoziation mit innovativer, kultureller Arbeit",
            "Zielgruppenansprache: Kulturinteressierte, Künstler*innen, Familien",
            "CSR-Engagement mit nachhaltiger Wirkung",
            "Möglichkeit für Event-Sponsoring und Naming Rights",
            "Networking mit der Münchner Kulturszene",
          ],
          pakete: [
            {
              name: "Community Sponsor",
              betrag: "ab 500€/Jahr",
              inhalt: [
                "Logo auf Website",
                "Erwähnung bei Veranstaltungen",
                "Newsletter-Erwähnung",
              ],
            },
            {
              name: "Event Sponsor",
              betrag: "ab 1.000€/Event",
              inhalt: [
                "Prominente Platzierung bei Veranstaltung",
                "Logo auf Werbematerialien",
                "Social Media Erwähnung",
                "Gastplätze bei Veranstaltung",
              ],
            },
            {
              name: "Hauptsponsor",
              betrag: "ab 2.500€/Jahr",
              inhalt: [
                "Alle Community Sponsor Leistungen",
                "Exklusive Naming Rights möglich",
                "Präsentation bei allen Veranstaltungen",
                "Individuelle Kooperationsmöglichkeiten",
                "Regelmäßige Updates und Einblicke",
              ],
            },
          ],
        },
      },
    },
    {
      id: "kooperation",
      title: "Kooperation",
      text: "Kultur, Bildung, Soziales, Stadtteil: Wir freuen uns über Partnerschaften auf Augenhöhe.",
      cta: "Kooperation starten",
      subject: "Kooperation",
    },
  ],
  kontakt: {
    intro: "Schreib uns – wir melden uns zeitnah zurück.",
    fields: {
      name: "Name",
      email: "Email",
      nachricht: "Nachricht",
      datenschutz: "Ich habe die Datenschutzhinweise gelesen.",
    },
    success: "Danke! Deine Nachricht ist bei uns gelandet (Demo).",
  },
  impressum: {
    title: "Impressum",
    content: "Platzhalter – bitte ersetzen",
    organisation: {
      organe: "Vorstand und Mitgliederversammlung.",
      vorstand: {
        struktur: "1. Vorsitz, stellv. Vorsitz, Schatzmeister, ggf. bis zu 4 Beisitzer",
        wahl: "Ehrenamtlich, Wahl für 2 Jahre",
        vertretung: "Vertretung nach außen: jedes Vorstandsmitglied allein vertretungsberechtigt",
        geschaeftsordnung: "Geschäftsordnung möglich (vom Vorstand), Genehmigung durch Mitgliederversammlung",
      },
      mitgliederversammlung: {
        haeufigkeit: "Mindestens 1× jährlich, schriftliche Einladung mit Tagesordnung, Frist 4 Wochen",
        ausserordentlich: "Außerordentliche Versammlung möglich/erforderlich unter bestimmten Voraussetzungen",
        beschlussfaehigkeit: "Beschlussfähigkeit unabhängig von Zahl der Anwesenden",
        mehrheiten: "Mehrheiten: grundsätzlich einfache Mehrheit; Satzungsänderung 2/3, Auflösung 4/5",
      },
      kassenpruefung: "Kassenprüfung wird für 2 Jahre gewählt; prüft Belege, Verbuchung und satzungs-/steuer-konforme Mittelverwendung und berichtet an die Mitgliederversammlung.",
      transparenz: {
        aemter: "Grundsätzlich ehrenamtlich. Bei Bedarf können Ämter entgeltlich oder mit pauschalierter Aufwandsentschädigung ausgeübt werden (Beschluss Mitgliederversammlung).",
        auftraege: "Der Vorstand kann Aufträge an Dritte gegen angemessene Vergütung vergeben",
        aufwendungsersatz: "Aufwendungsersatz nach § 670 BGB möglich (mit Belegen, Frist 3 Monate)",
        finanzordnung: "Details regelt eine Finanzordnung (durch Mitgliederversammlung).",
      },
      vermoegensbindung: "Bei Auflösung/Aufhebung oder Wegfall des Zwecks fällt das Vermögen an die Landeshauptstadt München zur gemeinnützigen Verwendung gemäß §2.",
    },
  },
  datenschutz: {
    title: "Datenschutz",
    content: "Platzhalter – bitte ersetzen",
    mitgliedsdaten: {
      erhebung: "Erhebung von Mitgliedsdaten (z. B. Name, Anschrift, Geburtsdatum, Telefon, E-Mail) für die Mitgliederverwaltung",
      verarbeitung: "Verarbeitung/Speicherung im Rahmen der Mitgliedschaft",
      weitergabe: "Weitergabe ggf. an Verband/ähnliche Organisation (falls Mitgliedschaft besteht)",
      veroeffentlichung: "Veröffentlichung nur bei Beschluss der Mitgliederversammlung und ohne Widerspruch des Mitglieds",
    },
  },
  satzung: {
    download: "/CAM_satzung.pdf",
    text: "Satzung (PDF)",
  },
  navigation: [
    { label: "Start", href: "/" },
    { label: "Zweck & Werte", href: "/zweck" },
    { label: "Angebote", href: "/angebote" },
    { label: "Ort", href: "/ort" },
    { label: "Aktuelles", href: "/aktuelles" },
    { label: "Mitmachen", href: "/mitmachen" },
    { label: "Kontakt", href: "/kontakt" },
  ],
} as const;
